POST http://localhost:8080/insert
Content-Type: application/json
Accept: application/json

{
    "name": "Carlo",
    "age": 31,
    "favouriteDestinations": {
        "destinations": [
            {
                "city": "Milan"
            },
            {
                "city": "London"
            }
        ]
    }
}

###

GET http://localhost:8080/find?name=Sergio
Content-Type: application/json
Accept: application/json

###

GET http://localhost:8080/retrieveUsers
Content-Type: application/json
Accept: application/json

###

GET http://localhost:8080/translations/en
Content-Type: application/json
Accept: application/json

###

POST http://localhost:8080/send
Content-Type: application/json
Accept: application/json

{
  "message": "I'm Davide!"
}