DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS
(
    ID int PRIMARY KEY AUTO_INCREMENT,
    USERNAME varchar(255),
    PASSWORD varchar(255),
    ADDRESS varchar(255)
);
DROP TABLE IF EXISTS ORDERS;
CREATE TABLE ORDERS
(
    ID int PRIMARY KEY AUTO_INCREMENT,
    TYPE varchar(255),
    USER_ID int,
    INSERTION_TIME date
)